[package]
name = "aoc-2015"
version = "0.1.0"
authors = ["Kris Verbeeck <kris_verbeeck@fastmail.fm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "day1"
path = "src/day1.rs"
